### PR TITLE
Submit jobs in a SystemD friendly manner

### PR DESCRIPTION
**Pull request by fretn**
* Added a consumable named mem_limit. This limits your jobs real memory usage through systemd whereas s/h_vmem limits your jobs virtual memory usage
  * Added CPUQuota through systemd. This can be enabled in a PE only when systemd usage is enabled. This sets your job's CPUQuota to *100%

There's also a version number upgrade, but it looks like your repository doesn't use the SoGE version numbers anymore, should I remove this code before you merge the request ?

### CODE REVIEW

**Comment by daimh** [comment]
Thanks a million! I will start to test your systemd patch on both Arch
and Void today and will get back to you in a few days. The reason is
while I hope it works better with systemd with your patch, I also hope
it works with the systemd haters. :)

Yes, I switched the SGE versioning to the git repository as the
building environment was switched to cmake+git. If it is easy for you,
could you please remove the version number patch? I can do it too if
you are busy.

Best,
Manhong

**Comment by fretn** [comment]
can you do it ? It's not that I'm lazy or so but I'm a bit confused on how to document the changes in the Changelog and other locations

for the systemd haters: all these changes are optional, if you don't enable systemd everything works as before

**Comment by fretn** [comment]
Note: this code was only tested on Centos 7, RHEL-8 and Fedora-34
I hope this works on Arch and Void linux

**Comment by daimh** [comment]
I will do it.

I will get back to you! Truly appreciate your contribution!

Best,
Manhong

**Comment by fretn** [comment]
The most difficult part of this pull request was done by Ondrej Valousek

**Pull request merged**
